CREATE DATABASE socialmedia;

USE socialmedia;

CREATE TABLE users(
 id INT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(100),
 password VARCHAR(100)
);

CREATE TABLE posts(
 id INT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(100),
 content TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);